const LINKS = [
  ["https://opencollective.com/dim", "Destiny Item Manager"],
  ["https://opencollective.com/webpack", "webpack"],
  ["https://opencollective.com/ankidroid", "AnkiDroid"],
  ["https://opencollective.com/darkreader", "Dark Reader"],
  ["https://opencollective.com/generator-jhipster", "JHipster"],
  ["https://opencollective.com/babel", "Babel"],
  ["https://opencollective.com/mochajs", "Mocha"],
  ["https://opencollective.com/11ty", "Eleventy"],
  ["https://opencollective.com/nest", "nest"],
  ["https://opencollective.com/socketio", "socket.io"],
  ["https://opencollective.com/qubes-os", "Qubes OS"],
  ["https://opencollective.com/jellyfin", "Jellyfin"],
  ["https://opencollective.com/core-js", "core-js"],
  ["https://opencollective.com/flybywire", "FlyByWire Simulations"],
  ["https://opencollective.com/date-fns", "date-fns"],
  ["https://opencollective.com/swiper", "Swiper"],
  ["https://opencollective.com/vuejs", "vue"],
  ["https://opencollective.com/obsproject", "Open Broadcaster Software"],
  ["https://opencollective.com/svelte", "Svelte"],
  ["https://opencollective.com/playframework", "Play Framework"],
  ["https://opencollective.com/manjaro", "manjaro"],
  ["https://opencollective.com/jest", "Jest"],
  ["https://opencollective.com/radarr", "Radarr"],
  [
    "https://opencollective.com/opencore-legacy-patcher",
    "OpenCore Legacy Patcher",
  ],
  ["https://opencollective.com/sonarr", "Sonarr"],
  ["https://opencollective.com/eslint", "ESLint"],
  ["https://opencollective.com/bootstrap-vue", "BootstrapVue"],
  ["https://opencollective.com/bower", "Bower"],
  ["https://opencollective.com/streetmix", "Streetmix"],
  ["https://opencollective.com/yiisoft", "Yii Software"],
  ["https://opencollective.com/openaddresses", "OpenAddresses"],
  ["https://opencollective.com/f-droid", "F-Droid ($)"],
  ["https://opencollective.com/crystal-lang", "Crystal Language"],
  ["https://opencollective.com/ionide", "Ionide"],
  ["https://opencollective.com/linuxserver", "LinuxServer"],
  ["https://opencollective.com/nuxtjs", "Nuxt"],
  ["https://opencollective.com/nodemon", "nodemon"],
  [
    "https://opencollective.com/lairdubois-opencutlist-sketchup-extension",
    "OpenCutList",
  ],
  ["https://opencollective.com/lucee", "Lucee"],
  ["https://opencollective.com/cider", "CIDER"],
  ["https://opencollective.com/fody", "Fody"],
  ["https://opencollective.com/mui-org", "MUI org"],
  ["https://opencollective.com/endeavouros", "EndeavourOS"],
  ["https://opencollective.com/prettier", "Prettier"],
  ["https://opencollective.com/cryptpad", "CryptPad"],
  ["https://opencollective.com/mastodon", "Mastodon"],
  ["https://opencollective.com/aurelia", "Aurelia"],
  ["https://opencollective.com/curl", "curl"],
  ["https://opencollective.com/gitea", "Gitea"],
  ["https://opencollective.com/framework7", "Framework7"],
  ["https://opencollective.com/stellarium", "Stellarium"],
  ["https://opencollective.com/bootstrap-table", "bootstrap-table"],
  ["https://opencollective.com/cadsketcher", "CAD Sketcher"],
  ["https://opencollective.com/open-web-docs", "Open Web Docs"],
  ["https://opencollective.com/dokku", "Dokku"],
  ["https://opencollective.com/spyder", "Spyder IDE"],
  ["https://opencollective.com/mongoose", "Mongoose.js"],
  ["https://opencollective.com/storybook", "Storybook"],
  ["https://opencollective.com/tusky", "Tusky"],
  ["https://opencollective.com/parcel", "Parcel"],
  ["https://opencollective.com/helix-editor", "Helix"],
  ["https://opencollective.com/vuetify", "Vuetify"],
  ["https://opencollective.com/mobx", "mobx"],
  ["https://opencollective.com/companion", "Bitfocus Companion"],
  ["https://opencollective.com/typeorm", "TypeORM"],
  ["https://opencollective.com/webform", "Webform module for Drupal"],
  ["https://opencollective.com/nerves-project", "Nerves Project"],
  ["https://opencollective.com/librecad", "LibreCAD"],
  ["https://opencollective.com/nim", "Nim"],
  ["https://opencollective.com/openipc", "OpenIPC"],
  ["https://opencollective.com/opensourcebim", "IfcOpenShell"],
  ["https://opencollective.com/neovim", "neovim"],
  ["https://opencollective.com/preact", "Preact"],
  ["https://opencollective.com/papermc", "PaperMC"],
  ["https://opencollective.com/vyos", "VyOS Project Collective"],
  ["https://opencollective.com/librenms", "LibreNMS"],
  ["https://opencollective.com/vapor", "Vapor"],
  ["https://opencollective.com/sinon", "sinon"],
  ["https://opencollective.com/grav", "Grav"],
  ["https://opencollective.com/cheerio", "cheerio"],
  ["https://opencollective.com/nz-federated-services", "NZ Federated Services"],
  ["https://opencollective.com/manjaro-us", "manjaro (US)"],
  ["https://opencollective.com/ruffle", "Ruffle"],
  ["https://opencollective.com/duplicati", "duplicati - inactive"],
  ["https://opencollective.com/kivy", "Kivy"],
  ["https://opencollective.com/chakra-ui", "Chakra UI"],
  ["https://opencollective.com/wikijs", "Wiki.js"],
  ["https://opencollective.com/keeweb", "KeeWeb"],
  ["https://opencollective.com/veloren", "Veloren"],
  ["https://opencollective.com/theodinproject", "The Odin Project"],
  ["https://opencollective.com/koin", "koin"],
  ["https://opencollective.com/friends-of-groovy", "Friends of Apache Groovy"],
  ["https://opencollective.com/keepassxc", "KeePassXC"],
  ["https://opencollective.com/ciderapp", "Cider Collective"],
  ["https://opencollective.com/fpv-wtf", "fpv.wtf"],
  ["https://opencollective.com/indieweb", "IndieWeb"],
  ["https://opencollective.com/bootstrap", "Bootstrap"],
  [
    "https://opencollective.com/secure-scuttlebutt-consortium",
    "Secure Scuttlebutt Consortium",
  ],
  ["https://opencollective.com/tosdr", "Terms of Service; Didn’t Read"],
  ["https://opencollective.com/parse-server", "Parse Platform"],
  ["https://opencollective.com/meet-coop", "Meet.coop"],
  ["https://opencollective.com/rubocop", "RuboCop"],
  ["https://opencollective.com/lidarr", "Lidarr"],
  ["https://opencollective.com/homebrew", "Homebrew"],
  ["https://opencollective.com/rsschool", "RS School"],
  ["https://opencollective.com/excalidraw", "excalidraw"],
  ["https://opencollective.com/expresslrs", "ExpressLRS"],
  ["https://opencollective.com/shields", "shields.io"],
  ["https://opencollective.com/omnivore", "Omnivore"],
  ["https://opencollective.com/blacksky", "Blacksky"],
  ["https://opencollective.com/lemmy", "Lemmy"],
  ["https://opencollective.com/typelevel", "Typelevel"],
  ["https://opencollective.com/rollup", "Rollup"],
  ["https://opencollective.com/jekyll", "Jekyll"],
  ["https://opencollective.com/postmarketos", "postmarketOS"],
  ["https://opencollective.com/assemblyscript", "AssemblyScript"],
  ["https://opencollective.com/avalonia", "Avalonia"],
  ["https://opencollective.com/redux-saga", "redux-saga"],
  ["https://opencollective.com/solid", "SolidJS"],
  ["https://opencollective.com/fider", "Fider"],
  ["https://opencollective.com/farmos", "farmOS"],
  ["https://opencollective.com/styled-components", "styled-components"],
  ["https://opencollective.com/astrodotbuild", "Astro"],
  ["https://opencollective.com/monitorcontrol", "MonitorControl"],
  ["https://opencollective.com/phalcon", "phalcon"],
  ["https://opencollective.com/opensourcedesign", "Open Source Design"],
  ["https://opencollective.com/asciidoctor", "Asciidoctor"],
  ["https://opencollective.com/octobox", "Octobox"],
  ["https://opencollective.com/pixelfed", "pixelfed"],
  ["https://opencollective.com/ampalibe", "Ampalibe"],
  ["https://opencollective.com/gotosocial", "GoToSocial"],
  ["https://opencollective.com/pnpm", "pnpm"],
  ["https://opencollective.com/laradock", "Laradock"],
  ["https://opencollective.com/gulpjs", "gulp"],
  ["https://opencollective.com/ngrx", "ngrx"],
  ["https://opencollective.com/panda3d", "Panda3D"],
  ["https://opencollective.com/regolith", "Regolith"],
  ["https://opencollective.com/axios", "axios"],
  ["https://opencollective.com/floating-ui", "Floating UI"],
  ["https://opencollective.com/ponyc", "Pony"],
  ["https://opencollective.com/grapesjs", "GrapesJS"],
  ["https://opencollective.com/meshtastic", "Meshtastic"],
  ["https://opencollective.com/firefish", "Firefish"],
  ["https://opencollective.com/openapi_generator", "OpenAPI Generator"],
  ["https://opencollective.com/cucumber", "Cucumber Open"],
  ["https://opencollective.com/openmined", "OpenMined"],
  ["https://opencollective.com/servo", "Servo"],
  ["https://opencollective.com/pixijs", "PixiJS - The HTML5 Creation Engine."],
  ["https://opencollective.com/revanced", "ReVanced"],
  ["https://opencollective.com/publii", "Publii"],
  ["https://opencollective.com/mautic", "Mautic"],
  ["https://opencollective.com/discordpy", "discord.py"],
  ["https://opencollective.com/lwjgl", "LWJGL"],
  [
    "https://opencollective.com/emacs-lsp",
    "Emacs Language Server Protocol Client",
  ],
  ["https://opencollective.com/antennapod", "AntennaPod"],
  ["https://opencollective.com/typegraphql", "TypeGraphQL"],
  ["https://opencollective.com/gitextensions", "gitextensions"],
  ["https://opencollective.com/tidalcycles", "TidalCycles"],
  ["https://opencollective.com/twohoursonelife", "Two Hours One Life"],
  [
    "https://opencollective.com/intellij-rainbow-brackets",
    "Intellij Rainbow Brackets",
  ],
  ["https://opencollective.com/electron", "electron"],
  ["https://opencollective.com/sixlabors", "Six Labors"],
  ["https://opencollective.com/owncast", "Owncast"],
  ["https://opencollective.com/xstate", "XState"],
  ["https://opencollective.com/caprover", "CapRover"],
  ["https://opencollective.com/redux-devtools-extension", "Redux DevTools"],
  ["https://opencollective.com/courtbouillon", "CourtBouillon"],
  ["https://opencollective.com/interruptorpt", "Interruptor"],
  ["https://opencollective.com/sindresorhus", "Sindre Sorhus"],
  ["https://opencollective.com/cyclejs", "Cycle.js"],
  ["https://opencollective.com/mollyim", "Molly"],
  ["https://opencollective.com/carbon", "Carbon"],
  ["https://opencollective.com/celery", "Celery"],
  ["https://opencollective.com/dlang", "dlang"],
  ["https://opencollective.com/reactiveui", "ReactiveUI"],
  ["https://opencollective.com/mixxx", "Mixxx DJ Software"],
  ["https://opencollective.com/unified", "unified"],
  ["https://opencollective.com/libreops", "LibreOps"],
  ["https://opencollective.com/vcr", "VCR"],
  ["https://opencollective.com/editorjs", "Editor.js"],
  ["https://opencollective.com/adnauseam", "AdNauseam"],
  ["https://opencollective.com/hledger", "hledger"],
  ["https://opencollective.com/funkwhale", "Funkwhale"],
  ["https://opencollective.com/nativescript", "NativeScript"],
  ["https://opencollective.com/daisyui", "daisyUI component library"],
  ["https://opencollective.com/openscad", "OpenSCAD"],
  ["https://opencollective.com/ancientbeast", "Ancient Beast 🐺"],
  ["https://opencollective.com/weg-li", "weg.li"],
  ["https://opencollective.com/freecad", "FreeCAD"],
  ["https://opencollective.com/mastodonnl", "Mastodon.nl"],
  ["https://opencollective.com/metamask", "MetaMask"],
  ["https://opencollective.com/husky", "Husky"],
  ["https://opencollective.com/goreleaser", "goreleaser"],
  ["https://opencollective.com/warzone2100", "Warzone 2100"],
  ["https://opencollective.com/cocnvim", "Coc.nvim"],
  ["https://opencollective.com/osarch", "OSArch - Open Source in AEC"],
  ["https://opencollective.com/the-a11y-project", "The A11Y Project"],
  ["https://opencollective.com/turf", "TurfJS"],
  ["https://opencollective.com/mudblazor", "MudBlazor"],
  ["https://opencollective.com/pug", "pug"],
  ["https://opencollective.com/xgboost", "DMLC/XGBoost"],
  ["https://opencollective.com/mvvmcross", "MvvmCross"],
  ["https://opencollective.com/react-hook-form", "React Hook Form"],
  ["https://opencollective.com/asyncapi", "AsyncAPI Initiative"],
  ["https://opencollective.com/localstack", "LocalStack"],
  ["https://opencollective.com/pytest", "pytest"],
  ["https://opencollective.com/serverest", "ServeRest"],
  ["https://opencollective.com/signalk", "Signal K"],
  ["https://opencollective.com/react-three-fiber", "react-three-fiber"],
  ["https://opencollective.com/rvm", "RVM"],
  ["https://opencollective.com/the-rockstor-project", "The Rockstor Project"],
  ["https://opencollective.com/react-spring", "react-spring"],
  ["https://opencollective.com/prismlauncher", "Prism Launcher"],
  ["https://opencollective.com/buddies-of-budgie", "Buddies of Budgie"],
  ["https://opencollective.com/concatenate", "Concatenate Conference"],
  ["https://opencollective.com/uptime-kuma", "Uptime Kuma"],
  ["https://opencollective.com/stylelint", "Stylelint"],
  ["https://opencollective.com/webdriverio", "WebdriverIO"],
  ["https://opencollective.com/ccxt", "CCXT"],
  ["https://opencollective.com/inferno", "inferno"],
  ["https://opencollective.com/browserslist", "Browserslist"],
  ["https://opencollective.com/bettermediauk", "Better Media"],
  ["https://opencollective.com/simplytestme", "SimplyTest.me"],
  ["https://opencollective.com/tiddlywiki", "TiddlyWiki"],
  ["https://opencollective.com/react-router", "React Router"],
  ["https://opencollective.com/php_codesniffer", "PHP CodeSniffer"],
  ["https://opencollective.com/ariakit", "Ariakit"],
  ["https://opencollective.com/nock", "nock"],
  ["https://opencollective.com/nix-community", "Nix Community"],
  ["https://opencollective.com/lambda-island", "Lambda Island Open Source"],
  ["https://opencollective.com/thecodebarbarian", "The Code Barbarian"],
  ["https://opencollective.com/tarkov-dev", "Tarkov Development Community"],
  ["https://opencollective.com/jmonkeyengine", "jMonkeyEngine"],
  ["https://opencollective.com/floccus", "floccus"],
  ["https://opencollective.com/jss", "JSS"],
  ["https://opencollective.com/firo", "Firo"],
  ["https://opencollective.com/thetorproject", "The Tor Project"],
  ["https://opencollective.com/react-pdf", "react-pdf"],
  ["https://opencollective.com/stc", "stc"],
  ["https://opencollective.com/poi", "poi"],
  ["https://opencollective.com/yew", "Yew"],
  ["https://opencollective.com/pypy", "PyPy"],
  ["https://opencollective.com/cncnet", "CnCNet"],
  ["https://opencollective.com/react-virtualized", "react-virtualized"],
  ["https://opencollective.com/json-schema", "JSON Schema"],
  ["https://opencollective.com/verdaccio", "verdaccio"],
  ["https://opencollective.com/nanoframework", ".NET nanoFramework"],
  ["https://opencollective.com/selfdefined", "Self Defined"],
  ["https://opencollective.com/rspec", "rspec"],
  [
    "https://opencollective.com/android-password-store",
    "Android Password Store",
  ],
  ["https://opencollective.com/archiveteam", "Archive Team"],
  ["https://opencollective.com/strapi", "Strapi"],
  ["https://opencollective.com/chaijs", "Chai"],
  ["https://opencollective.com/melpa", "MELPA"],
  ["https://opencollective.com/gtk-rs", "Gtk-rs"],
  ["https://opencollective.com/tabulapdf", "Tabula"],
  ["https://opencollective.com/yeoman", "Yeoman"],
  ["https://opencollective.com/ohmyzsh", "Oh My Zsh"],
  ["https://opencollective.com/yourls", "YOURLS"],
  ["https://opencollective.com/termux", "Termux"],
  ["https://opencollective.com/guppe-groups", "Guppe Groups Platform Co-op"],
  ["https://opencollective.com/emotion", "emotion"],
  ["https://opencollective.com/srs-server", "SRS"],
  ["https://opencollective.com/betonquest", "BetonQuest"],
  ["https://opencollective.com/pulsar-edit", "Pulsar Edit"],
  ["https://opencollective.com/kavita", "Kavita"],
  ["https://opencollective.com/code-for-philly", "Code for Philly"],
  ["https://opencollective.com/azuracast", "AzuraCast"],
  ["https://opencollective.com/discordjs", "discord.js"],
  ["https://opencollective.com/sous-chefs", "Sous-Chefs"],
  ["https://opencollective.com/koajs", "KoaJS"],
  ["https://opencollective.com/hapijs", "hapijs"],
  ["https://opencollective.com/zmkfirmware", "ZMK Firmware"],
  ["https://opencollective.com/emberjs", "Ember.js"],
  ["https://opencollective.com/openemr", "OpenEMR"],
  ["https://opencollective.com/chillicream", "ChilliCream"],
  ["https://opencollective.com/huntr", "huntr"],
  ["https://opencollective.com/london-clojurians", "London Clojurians"],
  ["https://opencollective.com/openlayers", "openlayers"],
  ["https://opencollective.com/libvips", "libvips"],
  ["https://opencollective.com/fast-endpoints", "FastEndpoints"],
  ["https://opencollective.com/premake", "Premake"],
  ["https://opencollective.com/livetl", "LiveTL"],
  ["https://opencollective.com/ajv", "Ajv"],
  ["https://opencollective.com/lint-staged", "lint-staged"],
  ["https://opencollective.com/acgn-stock", "acgn-stock"],
  ["https://opencollective.com/geysermc", "GeyserMC"],
  ["https://opencollective.com/randovania", "Randovania"],
  ["https://opencollective.com/actual", "Actual"],
  ["https://opencollective.com/universalviewer", "universalviewer"],
  ["https://opencollective.com/docusaurus", "Docusaurus"],
  ["https://opencollective.com/healthforxr", "Health for XR"],
  ["https://opencollective.com/yarnpkg", "Yarn"],
  ["https://opencollective.com/spotube", "Spotube"],
  ["https://opencollective.com/ant-design", "Ant Design"],
  ["https://opencollective.com/lem", "lem"],
  ["https://opencollective.com/modx", "MODX"],
  [
    "https://opencollective.com/ethical-source",
    "The Organization for Ethical Source",
  ],
  ["https://opencollective.com/crowbartools", "CrowbarTools"],
  ["https://opencollective.com/riot", "Riot.js"],
  ["https://opencollective.com/queerhaus", "Queer Haus"],
  ["https://opencollective.com/tuistfoundation", "Tuist Foundation"],
  ["https://opencollective.com/hydra-synth", "hydra community fund"],
  ["https://opencollective.com/debug", "debug"],
  ["https://opencollective.com/nextauth", "Auth.js"],
  ["https://opencollective.com/journahost", "journa.host"],
  ["https://opencollective.com/task", "Task"],
  ["https://opencollective.com/nannou", "nannou"],
  ["https://opencollective.com/acmesh", "acme.sh"],
  ["https://opencollective.com/xmonad", "xmonad"],
  ["https://opencollective.com/altair", "Altair GraphQL Client"],
  ["https://opencollective.com/pyodide", "Pyodide"],
  ["https://opencollective.com/ghost", "Ghost"],
  ["https://opencollective.com/mirakurun", "Mirakurun"],
  ["https://opencollective.com/peer", "PeerJS"],
  ["https://opencollective.com/feathers", "FeathersJS"],
  ["https://opencollective.com/known", "Known"],
  ["https://opencollective.com/perkeep", "Perkeep"],
  ["https://opencollective.com/fakerjs", "Faker"],
  ["https://opencollective.com/open5gs", "Open5GS"],
  ["https://opencollective.com/nivo", "nivo"],
  ["https://opencollective.com/clojure-lsp", "Clojure LSP"],
  ["https://opencollective.com/maplibre", "MapLibre"],
  ["https://opencollective.com/authelia-sponsors", "Authelia"],
  ["https://opencollective.com/tachyons", "Tachyons"],
  ["https://opencollective.com/responsively", "Responsively"],
  ["https://opencollective.com/kivymd", "KivyMD"],
  ["https://opencollective.com/drupal-mastodon", "Drupal Mastodon"],
  [
    "https://opencollective.com/ovenmediaengine",
    "OvenMediaEngine & OvenPlayer",
  ],
  ["https://opencollective.com/orchid", "Orchid for Laravel"],
  ["https://opencollective.com/docsify", "docsify"],
  ["https://opencollective.com/react-native-elements", "React Native Elements"],
  ["https://opencollective.com/thpatch", "Touhou Patch Center"],
  ["https://opencollective.com/orbitdb", "OrbitDB"],
  ["https://opencollective.com/ellie", "Ellie"],
  ["https://opencollective.com/cljdoc", "cljdoc"],
  ["https://opencollective.com/woodpecker-ci", "Woodpecker CI"],
  [
    "https://opencollective.com/open-streaming-platform",
    "Open Streaming Platform",
  ],
  ["https://opencollective.com/codeceptjs", "CodeceptJS"],
  ["https://opencollective.com/marshmallow", "marshmallow"],
  ["https://opencollective.com/spotiflyer", "SpotiFlyer"],
  ["https://opencollective.com/rom", "rom"],
  ["https://opencollective.com/nirvati", "Nirvati"],
  ["https://opencollective.com/dnscrypt", "dnscrypt"],
  ["https://opencollective.com/komga", "Komga"],
  ["https://opencollective.com/alvr", "ALVR"],
  ["https://opencollective.com/shapeshifter", "Shape Shifter"],
  ["https://opencollective.com/osca", "Open Source Community Africa"],
  ["https://opencollective.com/dat", "dat ecosystem"],
  ["https://opencollective.com/monnaie-libre", "Astroport"],
  ["https://opencollective.com/mithriljs", "Mithril.js"],
  ["https://opencollective.com/zinc-community", "Zinc Community"],
  ["https://opencollective.com/betterdisplay", "BetterDisplay"],
  ["https://opencollective.com/sequelize", "Sequelize"],
  ["https://opencollective.com/distribute-aid-usa", "Distribute Aid USA"],
  [
    "https://opencollective.com/drupal-diversity-and-inclusion",
    "Drupal Diversity & Inclusion",
  ],
  ["https://opencollective.com/clap", "Clap"],
  ["https://opencollective.com/cpprefjp", "cpprefjp"],
  ["https://opencollective.com/flashpointarchive", "Flashpoint Archive"],
  ["https://opencollective.com/communitybridge", "CommunityBridge"],
  ["https://opencollective.com/feddituk", "Feddit.uk"],
  ["https://opencollective.com/git-bug", "git-bug"],
  ["https://opencollective.com/piranhacms", "Piranha CMS"],
  ["https://opencollective.com/apex", "APEX"],
  ["https://opencollective.com/react-boilerplate", "react-boilerplate"],
  ["https://opencollective.com/manjaro-uk", "manjaro (UK)"],
  ["https://opencollective.com/sustainoss", "SustainOSS"],
  ["https://opencollective.com/coollabsio", "coolLabs"],
  ["https://opencollective.com/lottie", "Lottie"],
  [
    "https://opencollective.com/joomla-component-builder",
    "Joomla! Component Builder",
  ],
  ["https://opencollective.com/libsodium", "libsodium"],
  ["https://opencollective.com/cypressio", "Cypress.io"],
  ["https://opencollective.com/gureum", "구름 입력기"],
  ["https://opencollective.com/amplifying-fsharp", "Amplifying FSharp"],
  ["https://opencollective.com/cronus", "Cronus"],
  ["https://opencollective.com/catppuccin", "Catppuccin"],
  ["https://opencollective.com/craftjs", "craft.js"],
  ["https://opencollective.com/svgr", "SVGR"],
  ["https://opencollective.com/gbdev", "gbdev"],
  ["https://opencollective.com/erxes", "erxes Inc"],
  ["https://opencollective.com/xmake", "xmake"],
  ["https://opencollective.com/openpracticelibrary", "Open Practice Library"],
  ["https://opencollective.com/organicmaps", "Organic Maps"],
  ["https://opencollective.com/mswjs", "Mock Service Worker"],
  ["https://opencollective.com/peachcloud", "PeachCloud"],
  ["https://opencollective.com/eyedropper", "EyeDropper"],
  ["https://opencollective.com/weareopen", "We Are Open Projects"],
  ["https://opencollective.com/jrnl", "Jrnl"],
  ["https://opencollective.com/immer", "immer"],
  ["https://opencollective.com/biome", "Biome"],
  ["https://opencollective.com/project-sunrise", "Project Sunrise"],
  ["https://opencollective.com/colly", "Colly"],
  ["https://opencollective.com/csvhelper", "CsvHelper"],
  [
    "https://opencollective.com/atom-material-themes-and-plugins",
    "Atom Material Themes & Plugins",
  ],
  ["https://opencollective.com/visjs", "vis.js"],
  ["https://opencollective.com/choo", "choo"],
  [
    "https://opencollective.com/twisted-fields-research-collective",
    "Twisted Fields Research Collective",
  ],
  ["https://opencollective.com/quiltmc", "The Quilt Project"],
  ["https://opencollective.com/terser", "Terser"],
  ["https://opencollective.com/babashka", "babashka"],
  ["https://opencollective.com/vite", "Vite"],
  ["https://opencollective.com/metacpan-core", "MetaCPAN Core"],
  [
    "https://opencollective.com/effector",
    "effector — business logic with ease",
  ],
  ["https://opencollective.com/masscode", "massCode"],
  ["https://opencollective.com/hexo", "Hexo"],
  ["https://opencollective.com/hylo", "Hylo"],
  [
    "https://opencollective.com/electron-react-boilerplate-594",
    "electron-react-boilerplate",
  ],
  ["https://opencollective.com/dosbox-staging", "DOSBox Staging"],
  ["https://opencollective.com/dockstarter", "DockSTARTer"],
  ["https://opencollective.com/hoodie", "Hoodie"],
  ["https://opencollective.com/moleculer", "moleculer"],
  ["https://opencollective.com/elm-tooling", "Elm Tooling"],
  ["https://opencollective.com/zoneminder", "Zoneminder"],
  ["https://opencollective.com/m17-project", "M17 Project"],
  ["https://opencollective.com/x-ray", "x-ray"],
  ["https://opencollective.com/clipy", "Clipy"],
  ["https://opencollective.com/bundlephobia", "bundlephobia"],
  ["https://opencollective.com/thelounge", "The Lounge"],
  ["https://opencollective.com/ritabot-project", "RitaBot Project"],
  ["https://opencollective.com/dayjs", "Day.js"],
  ["https://opencollective.com/capawesome", "Capawesome"],
  ["https://opencollective.com/crossplatformkorea", "Cross-Platform Korea"],
  ["https://opencollective.com/allure-report", "Allure Report"],
  ["https://opencollective.com/sunrise-choir", "Sunrise Choir"],
  ["https://opencollective.com/synfig", "Synfig"],
  ["https://opencollective.com/lawnchair", "Lawnchair"],
  ["https://opencollective.com/qmk-firmware", "QMK Firmware"],
  ["https://opencollective.com/getferdi", "Ferdi"],
  ["https://opencollective.com/kingfisher", "Kingfisher"],
  ["https://opencollective.com/amberelec", "AmberELEC"],
  ["https://opencollective.com/kcanotify", "kcanotify"],
  ["https://opencollective.com/wolvic", "Wolvic"],
  ["https://opencollective.com/polybar", "polybar"],
  ["https://opencollective.com/graphql-net", "graphql-dotnet"],
  ["https://opencollective.com/elk", "Elk"],
  ["https://opencollective.com/openjscad", "OpenJSCAD.org"],
  ["https://opencollective.com/ant-design-vue", "Ant Design Vue"],
  ["https://opencollective.com/purpurmc", "PurpurMC"],
  ["https://opencollective.com/react-dropzone", "react-dropzone"],
  ["https://opencollective.com/apex-up", "up"],
  ["https://opencollective.com/cloudflarecollective", "Cloudflare Collective"],
  ["https://opencollective.com/opensourcediversity", "Open Source Diversity"],
  ["https://opencollective.com/openhd", "OpenHD"],
  ["https://opencollective.com/data-umbrella", "Data Umbrella"],
  ["https://opencollective.com/delta-chat", "Delta Chat collective"],
  ["https://opencollective.com/graphql-compose", "graphql-compose"],
  ["https://opencollective.com/reddthat", "Reddthat"],
  ["https://opencollective.com/marktext", "Mark Text"],
  ["https://opencollective.com/openapi-directory", "openapi-directory"],
  ["https://opencollective.com/openbeta", "OpenBeta"],
  ["https://opencollective.com/lyrion", "Lyrion"],
  ["https://opencollective.com/kumbiaphp", "KumbiaPHP"],
  ["https://opencollective.com/portmaster", "PortMaster"],
  ["https://opencollective.com/wheels-fw", "WHEELS.FW"],
  ["https://opencollective.com/spina", "Spina"],
  ["https://opencollective.com/code-settings-sync", "Code Settings Sync"],
  ["https://opencollective.com/julialang", "Julia Language"],
  ["https://opencollective.com/tabler", "Tabler"],
  ["https://opencollective.com/endora", "Endora"],
  ["https://opencollective.com/litiengine", "LITIENGINE"],
  ["https://opencollective.com/opsdroid", "opsdroid"],
  ["https://opencollective.com/hoppscotch", "Hoppscotch"],
  ["https://opencollective.com/nvim-treesitter", "Nvim Treesitter"],
  ["https://opencollective.com/censusreporter", "Census Reporter"],
  ["https://opencollective.com/democracyearth", "Democracy Earth Foundation"],
  ["https://opencollective.com/cockpit", "cockpit"],
  ["https://opencollective.com/swiftwasm", "SwiftWasm"],
  ["https://opencollective.com/jest-preview", "Jest Preview"],
  [
    "https://opencollective.com/ecorestorationalliance",
    "EcoRestoration Alliance",
  ],
  ["https://opencollective.com/reactjs-dallas", "ReactJS Dallas"],
  ["https://opencollective.com/applause-button", "Applause Button"],
  ["https://opencollective.com/meteor-up", "meteor-up"],
  ["https://opencollective.com/fossbilling", "FOSSBilling"],
  ["https://opencollective.com/xcodesapp", "XcodesApp"],
  ["https://opencollective.com/orangefox", "OrangeFox Recovery"],
  ["https://opencollective.com/react-toolbox", "React Toolbox!"],
  ["https://opencollective.com/webrtc-rs", "WebRTC.rs"],
  ["https://opencollective.com/boa", "Boa"],
  ["https://opencollective.com/systemjs", "SystemJS"],
  ["https://opencollective.com/urllib3", "urllib3"],
  ["https://opencollective.com/ngxs", "NGXS"],
  ["https://opencollective.com/ui-avatars", "UI Avatars"],
  ["https://opencollective.com/analysis-tools", "Analysis Tools"],
  ["https://opencollective.com/libpostal", "libpostal"],
  ["https://opencollective.com/brainjs", "brain.js"],
  ["https://opencollective.com/nusmods", "NUSMods"],
  ["https://opencollective.com/thewpcc", "The WPCC"],
  ["https://opencollective.com/laravel-admin", "laravel-admin"],
  ["https://opencollective.com/twilight", "Twilight"],
  ["https://opencollective.com/activitywatch", "ActivityWatch"],
  ["https://opencollective.com/openwhyd", "Openwhyd"],
  ["https://opencollective.com/react-pdf-wojtekmaj", "react-pdf"],
  ["https://opencollective.com/gdljs", "Guadalajara JS"],
  ["https://opencollective.com/moveable", "moveable"],
  ["https://opencollective.com/pester", "Pester"],
  ["https://opencollective.com/wintercms", "Winter CMS"],
  ["https://opencollective.com/create-react-app", "Create React App"],
  ["https://opencollective.com/codebuddies", "CodeBuddies"],
  ["https://opencollective.com/compodoc", "compodoc"],
  ["https://opencollective.com/sanic-org", "Sanic Community Organization"],
];

import playwright from "playwright";

async function fetchData() {
  const all: any[] = [];
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();

  for (const [url, name] of LINKS.slice(0, 5)) {
    const page = await context.newPage();
    await page.goto(url);
    const title = await page.title();

    const website = await page.evaluateHandle(() => {
      return document
        .querySelector('a[data-cy="social-link-0"]')
        ?.getAttribute("href");
    });

    const github = await page.evaluateHandle(() => {
      return document
        .querySelector('[data-cy="collective-hero"] a[href*="github"]')
        ?.getAttribute("href");
    });

    const text = await page.evaluateHandle(() => {
      const element = document.querySelector(
        '#section-contribute a[href*="ponsor"] button[data-cy="contribute-btn"]'
      );
      return element?.parentElement?.parentElement?.parentElement?.querySelector(
        '[data-cy="amount"]'
      )?.children[0]?.innerHTML;
    });

    if (!text) continue;

    all.push({
      url,
      name,
      title,
      price: (await text.jsonValue())?.slice(1),
      github,
      website,
    });
  }

  return all;
}

fetchData().then((data) => {
  console.log(data);
});
